server:
  port: 3000
db:
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "root"
  password: "root"
  database: "ishop"
  synchronize: true
  logging: true
#
# API DOCS
#
docs:
  API_PREFIX: "/api/v1"
  API_TITLE: "iShop"
  API_DESC: "iShop Api V1"
  API_VERSION: 1.0
#
#HEADER
#
header:
  X_REQUEST_ID: CRM-WEB-STAGING
  X_CLIENT_NAME: CRM-WEB
  X_COUNTRY_CODE: BD
  X_CLIENT_VERSION: 1.0
