application:
  name: "ishop"
  project: "ishop"
  organization: "QoveryCommunity"
databases:
  - type: "POSTGRESQL"
    name: "ishop"
    version: "12"
routers:
  - name: "main-ishop"
    routes:
      - application_name: "ishop"
        paths:
          - "/*"
