server:
  port: 3000
db:
  type: "postgres"
  host: "ishop-nq28ub3qcdib99ba-svc.qovery.io"
  port: 5432
  username: "postgres"
  password: "4fPxC3l42JHlQU4b"
  database: "postgres"
  synchronize: true
  logging: true
#
# API DOCS
#
docs:
  API_PREFIX: "/api/v1"
  API_TITLE: "iShop"
  API_DESC: "iShop Api V1"
  API_VERSION: 1.0
#
#HEADER
#
header:
  X_REQUEST_ID: CRM-WEB-STAGING
  X_CLIENT_NAME: CRM-WEB
  X_COUNTRY_CODE: BD
  X_CLIENT_VERSION: 1.0

#
#JWT
#
JWTSecret: "topSecret51"
saltRound: 10

#
# Mail Credential
#
MAIL_HOST: "smtp.gmail.com"
MAIL_PORT: 465
MAIL_SECURE: true
MAIL_USER: "searchsparrow@gmail.com"
MAIL_PASSWORD: "ZKZ78S98VK@h1"
MAIL_FROM: "PSL <JOBAYER@gmail.com>"
